### ISSUE TITLE
Не отображается клавиатура в iOS

### ISSUE THREAD

**Issue by archived001** [idrats/yandex_kassa#10]
Карту можно ввести только из буфера обмена, на попытки нажатия клавиш не реагирует. В Android все корректно работает. 

Проблема в плагине или в https://github.com/yandex-money/yandex-checkout-payments-swift?

https://github.com/kcrebound/yandex_kassa_example - вот тут пример, 4.1.0 версия

![image](https://user-images.githubusercontent.com/151965/99428810-f291bc80-2928-11eb-8f9c-e683060ed6ff.png)

**Comment by idrats** [comment]
Здравствуйте!
Спасибо за ваш пул-реквест. Я постараюсь в ближайшее время принять его. 
На новой версии SDK яндекса я еще не запускал плагин. Возможно, что проблема действительно на их стороне

**Comment by archived001** [comment]
попробовал с бука собрать пример, заработало нормально, перепроверю еще раз этот момент

**Comment by rtoshmukhamedov** [comment]
Это наверно из за IPhone simulator. Клавиатура отключилась просто.
